# Generated by Django 2.1.5 on 2019-02-21 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20190221_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
